language: go
go:
        - 1.9.x
        - 1.10.x
        - 1.11.x
        - stable
script:
        - go get -t ./...
        - go test ./...
        - go test -race ./...
        - go vet ./...
        - diff -u <(echo -n) <(gofmt -d -s .)
        - diff -u <(echo -n) <(./scripts/autogen_licences.sh .)
after_success:
        - ./scripts/coverage.sh
